# Generated by Django 5.1.4 on 2025-01-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_key',
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
    ]
