# Generated by Django 5.1.4 on 2025-01-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
